#!/usr/bin/env python3
"""Collect domain-decomposition solver runtimes.

The fair comparisons are inside the new domain-decomposition set:

- pure MPI domain vs hybrid MPI+OpenMP within the same language
- C vs C++ vs Python for the same domain-decomposition case

The old benchmark runtimes are kept only as context. They come from the original
SIMPLE-style serial/OpenMP solver family. Old case-level MPI sweep rows are intentionally
removed from the cleaned package because they are not domain decomposition and confused the story.
"""
from __future__ import annotations

import csv
from pathlib import Path
from typing import Dict, List, Optional

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "comparison" / "results" / "domain_clean"
OUT.mkdir(parents=True, exist_ok=True)

SUMMARY_FILES = [
    ("c_mpi_domain", ROOT / "c" / "mpi_domain" / "results" / "data" / "c_mpi_domain_summary.csv", "c_serial"),
    ("c_hybrid_mpi_openmp_domain", ROOT / "c" / "hybrid_mpi_openmp" / "results" / "data" / "c_hybrid_mpi_openmp_domain_summary.csv", "c_openmp_t4"),
    ("cpp_mpi_domain", ROOT / "cpp" / "mpi_domain" / "results" / "data" / "mpi_domain_summary.csv", "cpp_serial"),
    ("cpp_hybrid_mpi_openmp_domain", ROOT / "cpp" / "hybrid_mpi_openmp" / "results" / "data" / "hybrid_domain_summary.csv", "cpp_openmp_t4"),
    ("python_mpi_domain", ROOT / "python" / "mpi_domain" / "results" / "data" / "python_mpi_domain_summary.csv", "python_vectorized"),
    ("python_hybrid_mpi_threaded_domain", ROOT / "python" / "hybrid_mpi_openmp" / "results" / "data" / "python_hybrid_mpi_threaded_summary.csv", "python_vectorized"),
]

OLD_SUMMARY = ROOT / "comparison" / "results" / "final_clean" / "runtime_summary_fixed.csv"
REMOVED_OLD_MPI = {"c_mpi", "cpp_mpi", "python_mpi"}


def read_csv(path: Path) -> List[Dict[str, str]]:
    if not path.exists() or path.stat().st_size == 0:
        return []
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def pick(row: Dict[str, str], *names: str, default: str = "") -> str:
    for name in names:
        if name in row and row[name] not in (None, ""):
            return row[name]
    return default


def to_float(value: str) -> Optional[float]:
    try:
        return float(value)
    except Exception:
        return None


def load_old_medians() -> Dict[str, float]:
    old: Dict[str, float] = {}
    for row in read_csv(OLD_SUMMARY):
        solver = row.get("solver_group", "")
        if solver in REMOVED_OLD_MPI:
            continue
        val = to_float(row.get("median_runtime_s", ""))
        if solver and val is not None:
            old[solver] = val
    return old


def collect_domain_rows() -> List[Dict[str, str]]:
    rows: List[Dict[str, str]] = []
    old = load_old_medians()
    for solver_name, path, old_ref in SUMMARY_FILES:
        for raw in read_csv(path):
            runtime = to_float(pick(raw, "Runtime_s", "runtime_s"))
            old_median = old.get(old_ref)
            ratio = ""
            if runtime and old_median:
                ratio = f"{old_median / runtime:.6g}"
            rows.append({
                "solver_group": solver_name,
                "language": solver_name.split("_")[0],
                "parallel_type": "hybrid_mpi_shared_memory" if "hybrid" in solver_name else "pure_mpi_domain",
                "N": pick(raw, "N"),
                "Re": pick(raw, "Re"),
                "scheme": pick(raw, "Scheme", "scheme"),
                "steps": pick(raw, "Steps", "steps"),
                "poisson_iters": pick(raw, "PoissonIters", "poisson_iters"),
                "mpi_ranks": pick(raw, "MPIRanks", "MPI_Ranks", "mpi_ranks"),
                "threads_per_rank": pick(raw, "OpenMPThreads", "OpenMP_Threads", "ThreadsPerRank", "threads_per_rank", default="1"),
                "runtime_s": f"{runtime:.10f}" if runtime is not None else "",
                "old_context_solver": old_ref,
                "old_context_median_runtime_s": f"{old_median:.10f}" if old_median is not None else "",
                "ratio_old_context_median_over_new_runtime": ratio,
                "summary_file": str(path.relative_to(ROOT)),
            })
    return rows


def write_csv(path: Path, rows: List[Dict[str, str]]) -> None:
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)


def write_report(rows: List[Dict[str, str]]) -> None:
    report = OUT / "domain_runtime_report.md"
    lines: List[str] = []
    lines.append("# Domain-Decomposition Runtime Report")
    lines.append("")
    lines.append("Generated by `scripts/compare_domain_solver_times.py`.")
    lines.append("")
    lines.append("## What is being compared")
    lines.append("")
    lines.append("The fair comparison is the six-solver domain-decomposition matrix:")
    lines.append("")
    lines.append("| Language | Pure MPI domain | Hybrid version |")
    lines.append("|---|---|---|")
    lines.append("| C | `c_mpi_domain` | `c_hybrid_mpi_openmp_domain` |")
    lines.append("| C++ | `cpp_mpi_domain` | `cpp_hybrid_mpi_openmp_domain` |")
    lines.append("| Python | `python_mpi_domain` | `python_hybrid_mpi_threaded_domain` |")
    lines.append("")
    lines.append("All six are intended to use the same streamfunction-vorticity lid-driven-cavity formulation, row-wise decomposition, ghost-row exchange, global reductions, and identical case settings.")
    lines.append("")
    lines.append("## Important note about old times")
    lines.append("")
    lines.append("The old timings are shown only as context. They come from the original SIMPLE-style serial/OpenMP benchmark. Old case-level MPI sweep results were removed from this cleaned package because they were not domain decomposition.")
    lines.append("")
    if not rows:
        lines.append("No domain-decomposition summary CSV files were found yet. Run `bash scripts/run_domain_solver_benchmark.sh` first.")
        report.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return
    lines.append("## New domain-decomposition solver times")
    lines.append("")
    lines.append("| Solver | N | Re | Ranks | Threads/rank | Steps | Runtime [s] | Old context solver | Old median [s] | Old/new ratio |")
    lines.append("|---|---:|---:|---:|---:|---:|---:|---|---:|---:|")
    for r in rows:
        lines.append(
            f"| `{r['solver_group']}` | {r['N']} | {r['Re']} | {r['mpi_ranks']} | {r['threads_per_rank']} | {r['steps']} | {r['runtime_s']} | `{r['old_context_solver']}` | {r['old_context_median_runtime_s']} | {r['ratio_old_context_median_over_new_runtime']} |"
        )
    lines.append("")
    lines.append("## Fair conclusions to draw")
    lines.append("")
    lines.append("- Compare `c_mpi_domain` vs `c_hybrid_mpi_openmp_domain`.")
    lines.append("- Compare `cpp_mpi_domain` vs `cpp_hybrid_mpi_openmp_domain`.")
    lines.append("- Compare `python_mpi_domain` vs `python_hybrid_mpi_threaded_domain`.")
    lines.append("- Compare C vs C++ vs Python only for the same `N`, `Re`, ranks, steps, and Poisson iterations.")
    report.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    rows = collect_domain_rows()
    write_csv(OUT / "domain_solver_times.csv", rows)
    write_csv(OUT / "domain_vs_old_runtime_context.csv", rows)
    write_report(rows)
    print(f"Wrote {OUT / 'domain_solver_times.csv'}")
    print(f"Wrote {OUT / 'domain_vs_old_runtime_context.csv'}")
    print(f"Wrote {OUT / 'domain_runtime_report.md'}")
    if not rows:
        print("No domain rows found yet. Run scripts/run_domain_solver_benchmark.sh first.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
