#!/usr/bin/env python3
from __future__ import annotations
import csv
from pathlib import Path
from collections import defaultdict

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "comparison" / "results" / "domain_kernel_matrix"
OUT.mkdir(parents=True, exist_ok=True)

ENTRIES = [('c_mpi_domain_looped', 'c', 'mpi', 'looped', 'c/mpi_domain_looped/results/data/c_mpi_domain_looped_summary.csv'), ('c_mpi_domain_vectorized', 'c', 'mpi', 'vectorized', 'c/mpi_domain_vectorized/results/data/c_mpi_domain_vectorized_summary.csv'), ('c_hybrid_mpi_openmp_looped', 'c', 'hybrid', 'looped', 'c/hybrid_mpi_openmp_looped/results/data/c_hybrid_mpi_openmp_looped_summary.csv'), ('c_hybrid_mpi_openmp_vectorized', 'c', 'hybrid', 'vectorized', 'c/hybrid_mpi_openmp_vectorized/results/data/c_hybrid_mpi_openmp_vectorized_summary.csv'), ('cpp_mpi_domain_looped', 'cpp', 'mpi', 'looped', 'cpp/mpi_domain_looped/results/data/cpp_mpi_domain_looped_summary.csv'), ('cpp_mpi_domain_vectorized', 'cpp', 'mpi', 'vectorized', 'cpp/mpi_domain_vectorized/results/data/cpp_mpi_domain_vectorized_summary.csv'), ('cpp_hybrid_mpi_openmp_looped', 'cpp', 'hybrid', 'looped', 'cpp/hybrid_mpi_openmp_looped/results/data/cpp_hybrid_mpi_openmp_looped_summary.csv'), ('cpp_hybrid_mpi_openmp_vectorized', 'cpp', 'hybrid', 'vectorized', 'cpp/hybrid_mpi_openmp_vectorized/results/data/cpp_hybrid_mpi_openmp_vectorized_summary.csv'), ('python_mpi_domain_looped', 'python', 'mpi', 'looped', 'python/mpi_domain_looped/results/data/python_mpi_domain_looped_summary.csv'), ('python_mpi_domain_vectorized', 'python', 'mpi', 'vectorized', 'python/mpi_domain_vectorized/results/data/python_mpi_domain_vectorized_summary.csv'), ('python_hybrid_mpi_threaded_looped', 'python', 'hybrid', 'looped', 'python/hybrid_mpi_openmp_looped/results/data/python_hybrid_mpi_threaded_looped_summary.csv'), ('python_hybrid_mpi_threaded_vectorized', 'python', 'hybrid', 'vectorized', 'python/hybrid_mpi_openmp_vectorized/results/data/python_hybrid_mpi_threaded_vectorized_summary.csv')]


def read_csv(path: Path):
    if not path.exists() or path.stat().st_size == 0:
        return []
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))

def pick(row, *names, default=""):
    for n in names:
        if n in row and row[n] not in (None, ""):
            return row[n]
    return default

def fnum(x):
    try:
        return float(x)
    except Exception:
        return None

rows = []
for impl, lang, parallel, kernel, rel in ENTRIES:
    for r in read_csv(ROOT / rel):
        runtime = fnum(pick(r, "Runtime_s", "runtime_s"))
        rows.append({
            "solver_group": impl,
            "language": lang,
            "parallel_type": "mpi_domain" if parallel == "mpi" else "hybrid_mpi_shared_memory",
            "kernel_style": kernel,
            "N": pick(r, "N"),
            "Re": pick(r, "Re"),
            "scheme": pick(r, "Scheme", "scheme"),
            "steps": pick(r, "Steps", "steps"),
            "poisson_iters": pick(r, "PoissonIters", "poisson_iters"),
            "mpi_ranks": pick(r, "MPIRanks", "MPI_Ranks", "mpi_ranks"),
            "threads_per_rank": pick(r, "OpenMPThreads", "OpenMP_Threads", "ThreadsPerRank", "threads_per_rank", default="1"),
            "runtime_s": f"{runtime:.10f}" if runtime is not None else "",
            "summary_file": rel,
        })

# Derived speedups inside same language/parallel family.
lookup = {(r["language"], r["parallel_type"], r["kernel_style"]): fnum(r["runtime_s"]) for r in rows}
for r in rows:
    lang = r["language"]
    par = r["parallel_type"]
    runtime = fnum(r["runtime_s"])
    loop_runtime = lookup.get((lang, par, "looped"))
    mpi_runtime_same_kernel = lookup.get((lang, "mpi_domain", r["kernel_style"]))
    r["speedup_vs_looped_same_parallel"] = ""
    if runtime and loop_runtime and r["kernel_style"] == "vectorized":
        r["speedup_vs_looped_same_parallel"] = f"{loop_runtime/runtime:.6g}"
    r["hybrid_speedup_vs_mpi_same_kernel"] = ""
    if runtime and mpi_runtime_same_kernel and r["parallel_type"] == "hybrid_mpi_shared_memory":
        r["hybrid_speedup_vs_mpi_same_kernel"] = f"{mpi_runtime_same_kernel/runtime:.6g}"

out_csv = OUT / "domain_kernel_matrix_times.csv"
if rows:
    keys = list(rows[0].keys())
    with out_csv.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=keys)
        w.writeheader(); w.writerows(rows)
else:
    out_csv.write_text("", encoding="utf-8")

report = OUT / "domain_kernel_matrix_report.md"
lines = []
lines.append("# Domain-Decomposition Kernel Matrix Report")
lines.append("")
lines.append("Generated by `scripts/compare_domain_kernel_matrix.py`.")
lines.append("")
lines.append("## Solver matrix")
lines.append("")
lines.append("| Language | MPI looped | MPI vectorized | Hybrid looped | Hybrid vectorized |")
lines.append("|---|---|---|---|---|")
lines.append("| C | `c/mpi_domain_looped` | `c/mpi_domain_vectorized` | `c/hybrid_mpi_openmp_looped` | `c/hybrid_mpi_openmp_vectorized` |")
lines.append("| C++ | `cpp/mpi_domain_looped` | `cpp/mpi_domain_vectorized` | `cpp/hybrid_mpi_openmp_looped` | `cpp/hybrid_mpi_openmp_vectorized` |")
lines.append("| Python | `python/mpi_domain_looped` | `python/mpi_domain_vectorized` | `python/hybrid_mpi_openmp_looped` | `python/hybrid_mpi_openmp_vectorized` |")
lines.append("")
lines.append("All matrix solvers use the same streamfunction-vorticity formulation, row-wise MPI domain decomposition, ghost-row exchange, global reductions, and rank-0 field gathering.")
lines.append("")
lines.append("## Important interpretation")
lines.append("")
lines.append("- `looped` means explicit local-loop kernels.")
lines.append("- `vectorized` means SIMD/vectorization-friendly kernels in C/C++ and NumPy-slice kernels in Python.")
lines.append("- `hybrid` means MPI between ranks plus shared-memory work inside a rank. In Python this is the closest honest equivalent: mpi4py plus optional Numba/threaded kernels where available.")
lines.append("- Compare all 12 only when `N`, `Re`, ranks, steps, Poisson iterations, and scheme are identical.")
lines.append("")
if not rows:
    lines.append("No summary CSVs found yet. Run `bash scripts/run_domain_kernel_matrix.sh` first.")
else:
    lines.append("## Runtime table")
    lines.append("")
    lines.append("| Solver | N | Re | Ranks | Threads/rank | Kernel | Runtime [s] | Vec speedup vs looped | Hybrid speedup vs MPI |")
    lines.append("|---|---:|---:|---:|---:|---|---:|---:|---:|")
    for r in rows:
        lines.append(f"| `{r['solver_group']}` | {r['N']} | {r['Re']} | {r['mpi_ranks']} | {r['threads_per_rank']} | {r['kernel_style']} | {r['runtime_s']} | {r['speedup_vs_looped_same_parallel']} | {r['hybrid_speedup_vs_mpi_same_kernel']} |")
    lines.append("")
    lines.append("## Fair comparison questions")
    lines.append("")
    lines.append("1. Inside each language: does vectorization help over looped kernels?")
    lines.append("2. Inside each language and kernel style: does hybrid MPI+shared-memory help over pure MPI?")
    lines.append("3. Across languages: compare only the same parallel type and same kernel style.")
report.write_text("\n".join(lines)+"\n", encoding="utf-8")
print(f"Wrote {out_csv}")
print(f"Wrote {report}")
if not rows:
    print("No domain-kernel matrix rows found yet. Run scripts/run_domain_kernel_matrix.sh first.")
