#!/usr/bin/env python3
from __future__ import annotations
import csv, math, statistics
from pathlib import Path
from collections import defaultdict

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'comparison' / 'results' / 'mega_project'
OUT.mkdir(parents=True, exist_ok=True)


def read_csv(path: Path):
    if not path.exists() or path.stat().st_size == 0:
        return []
    try:
        with path.open(newline='', encoding='utf-8') as f:
            return list(csv.DictReader(f))
    except Exception:
        return []


def fnum(x):
    try:
        if x in (None, ''):
            return None
        return float(x)
    except Exception:
        return None


def write_csv(path: Path, rows: list[dict]):
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text('', encoding='utf-8')
        return
    fields = list(rows[0].keys())
    with path.open('w', newline='', encoding='utf-8') as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader(); w.writerows(rows)


def summarize_original_raw():
    raw_dir = ROOT / 'comparison' / 'results' / 'raw'
    rows = []
    for path in sorted(raw_dir.glob('*.csv')):
        data = read_csv(path)
        runtimes = []
        ok = 0
        for r in data:
            # Support both original and standardized columns.
            rt = fnum(r.get('Runtime_s') or r.get('runtime_s') or r.get('runtime_std'))
            if rt is not None:
                runtimes.append(rt)
            status = (r.get('Status') or r.get('status') or '').lower()
            if status in ('complete', 'success', 'ok', 'converged') or status == '':
                ok += 1
        rows.append({
            'source_file': str(path.relative_to(ROOT)),
            'rows': len(data),
            'successful_or_recorded_rows': ok,
            'runtime_median_s': f'{statistics.median(runtimes):.10g}' if runtimes else '',
            'runtime_min_s': f'{min(runtimes):.10g}' if runtimes else '',
            'runtime_max_s': f'{max(runtimes):.10g}' if runtimes else '',
        })
    write_csv(OUT / 'original_full_benchmark_file_summary.csv', rows)
    return rows


def summarize_existing_final_clean():
    p = ROOT / 'comparison' / 'results' / 'final_clean' / 'runtime_summary_fixed.csv'
    rows = read_csv(p)
    # Keep as a copied context table if present.
    if rows:
        write_csv(OUT / 'old_final_clean_runtime_context.csv', rows)
    return rows


def summarize_domain_strong_scaling():
    p = ROOT / 'comparison' / 'results' / 'strong_scaling' / 'strong_scaling_summary.csv'
    rows = read_csv(p)
    if rows:
        write_csv(OUT / 'domain_strong_scaling_summary.csv', rows)
    # Build best table by case + solver using median runtime.
    best = []
    groups = defaultdict(list)
    for r in rows:
        groups[(r.get('case_id',''), r.get('solver_group',''))].append(r)
    for (case_id, solver), vals in sorted(groups.items()):
        vals2 = [v for v in vals if fnum(v.get('runtime_median_s')) is not None]
        if not vals2:
            continue
        b = min(vals2, key=lambda v: fnum(v.get('runtime_median_s')))
        best.append({
            'case_id': case_id,
            'solver_group': solver,
            'language': b.get('language',''),
            'parallel_model': b.get('parallel_model',''),
            'kernel_style': b.get('kernel_style',''),
            'N': b.get('N',''),
            'Re': b.get('Re',''),
            'scheme': b.get('scheme',''),
            'pressure_or_formulation': b.get('pressure',''),
            'best_total_cores': b.get('total_cores',''),
            'mpi_ranks': b.get('mpi_ranks',''),
            'threads_per_rank': b.get('threads_per_rank',''),
            'best_runtime_median_s': b.get('runtime_median_s',''),
            'speedup_vs_baseline': b.get('speedup_vs_baseline',''),
            'parallel_efficiency': b.get('parallel_efficiency',''),
        })
    write_csv(OUT / 'domain_best_runtime_by_case_solver.csv', best)
    return rows, best


def make_report(original_rows, final_clean_rows, strong_rows, best_rows):
    lines = []
    lines.append('# Mega Project Benchmark Report')
    lines.append('')
    lines.append('Generated by `scripts/mega_project_report.py`.')
    lines.append('')
    lines.append('## What this mega study contains')
    lines.append('')
    lines.append('1. Original SIMPLE-style benchmark family: serial, OpenMP, Python looped/vectorized, Octave looped/vectorized, and CUDA where available.')
    lines.append('2. New domain-decomposition solver matrix: C, C++, and Python; pure MPI and hybrid; looped and vectorized kernel styles.')
    lines.append('3. Strong scaling from 1 to 16 total ranks/cores for MPI, OpenMP-only domain, and hybrid runs.')
    lines.append('')
    lines.append('## Important interpretation note')
    lines.append('')
    lines.append('- The original benchmark family and the new domain-decomposition family are both lid-driven cavity studies, but they are not identical numerical implementations.')
    lines.append('- The clean apples-to-apples comparison for the new work is inside the domain-decomposition matrix itself.')
    lines.append('- The old original benchmark results should be used as historical/runtime context, not as a strict proof that one numerical formulation is faster than the other.')
    lines.append('')
    lines.append('## Original full benchmark outputs')
    lines.append('')
    if not original_rows:
        if final_clean_rows:
            lines.append('Original benchmark arrays were not regenerated in this run. Existing final-clean results were found and are used as the old benchmark context.')
        else:
            lines.append('No original raw CSV files or final-clean runtime context were found yet.')
    else:
        lines.append('| File | Rows | Median runtime [s] | Min [s] | Max [s] |')
        lines.append('|---|---:|---:|---:|---:|')
        for r in original_rows:
            lines.append(f"| `{r['source_file']}` | {r['rows']} | {r['runtime_median_s']} | {r['runtime_min_s']} | {r['runtime_max_s']} |")
    lines.append('')
    lines.append('## Existing final-clean runtime context')
    lines.append('')
    if final_clean_rows:
        lines.append(f'Found `{len(final_clean_rows)}` rows in `comparison/results/final_clean/runtime_summary_fixed.csv`. A copy is saved as `old_final_clean_runtime_context.csv`.')
    else:
        lines.append('No final-clean runtime context table found.')
    lines.append('')
    lines.append('## Domain-decomposition strong-scaling outputs')
    lines.append('')
    if not strong_rows:
        lines.append('No strong-scaling rows found yet. Run `scripts/run_strong_scaling_all.sh` or the huge project Slurm submitter first.')
    else:
        unique_cases = sorted(set(r.get('case_id','') for r in strong_rows))
        unique_solvers = sorted(set(r.get('solver_group','') for r in strong_rows))
        lines.append(f'- Strong-scaling timing rows: `{len(strong_rows)}`')
        lines.append(f'- Cases: `{len(unique_cases)}`')
        lines.append(f'- Solver groups: `{len(unique_solvers)}`')
        lines.append('')
        lines.append('### Best domain runtime by case and solver')
        lines.append('')
        lines.append('| Case | Solver | Model | Kernel | Best cores | Runtime median [s] | Speedup | Efficiency |')
        lines.append('|---|---|---|---|---:|---:|---:|---:|')
        for r in best_rows[:300]:
            lines.append(f"| `{r['case_id']}` | `{r['solver_group']}` | {r['parallel_model']} | {r['kernel_style']} | {r['best_total_cores']} | {r['best_runtime_median_s']} | {r['speedup_vs_baseline']} | {r['parallel_efficiency']} |")
        if len(best_rows) > 300:
            lines.append(f'\nTable truncated in Markdown at 300 rows. Full CSV: `domain_best_runtime_by_case_solver.csv`.')
    lines.append('')
    lines.append('## Output files')
    lines.append('')
    lines.append('- `comparison/results/mega_project/original_full_benchmark_file_summary.csv`')
    lines.append('- `comparison/results/mega_project/old_final_clean_runtime_context.csv`')
    lines.append('- `comparison/results/mega_project/domain_strong_scaling_summary.csv`')
    lines.append('- `comparison/results/mega_project/domain_best_runtime_by_case_solver.csv`')
    lines.append('- `comparison/results/mega_project/mega_project_report.md`')
    lines.append('')
    lines.append('## Recommended project wording')
    lines.append('')
    lines.append('This repository contains a full lid-driven cavity CFD/HPC benchmark suite: original SIMPLE-style serial/OpenMP/Python/Octave/CUDA implementations, plus a separate domain-decomposition solver matrix in C, C++, and Python using pure MPI and hybrid MPI/shared-memory execution with looped and vectorized kernel variants. The study includes full parameter sweeps and 1-to-16-core strong-scaling analysis.')
    (OUT / 'mega_project_report.md').write_text('\n'.join(lines) + '\n', encoding='utf-8')


def main() -> int:
    original = summarize_original_raw()
    final_clean = summarize_existing_final_clean()
    strong, best = summarize_domain_strong_scaling()
    make_report(original, final_clean, strong, best)
    print(f'Wrote {OUT / "mega_project_report.md"}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
